apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 10m
  chart:
    spec:
      chart: rancher
      version: "2.12.3"
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
      interval: 10m
  values:
    replicaCount: 2
      hostname: ranch.heroaero.net
      ingress:
        enabled: true
        ingressClassName: traefik
        pathType: ImplementationSpecific
        path: "/"
        servicePort: 80

        #extraAnnotations:
        #cert-manager.io/cluster-issuer: letsencrypt-prod
        #nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

      tls:
        #source: letsEncrypt
        #secretName: tls-rancher-ingress
