apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: twingate
spec:
  chart:
    spec:
      chart: connector
      version: "0.1.32"
      sourceRef:
        kind: HelmRepository
        name: twingate
        namespace: flux-system
  interval: 1h
  valuesFrom:
    - kind: Secret
      name: twingate
      valuesKey: values.yaml
  values:
    connector:
      network: "aerodev"
