apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: twingate
  namespace: network
spec:
  chart:
    spec:
      chart: connector
      version: "0.1.32"
      sourceRef:
        kind: HelmRepository
        name: twingate
        namespace: flux-system
  interval: 1h
  values:
    connector:
      network: "aerodev"
      existingSecret: "twingate-credentials"
