checks:
  # Exclude some checks that are too strict for homelab
  exclude:
    - "unset-cpu-requirements"      # Homelab doesn't need strict CPU limits
    - "no-read-only-root-fs"        # Many apps need writable root
    - "run-as-non-root"             # Will fix incrementally
    - "no-extensions-v1beta"        # Not using beta APIs

  # Include important security checks
  include:
    - "dangling-service"
    - "default-service-account"
    - "deprecated-service-account-field"
    - "docker-sock"
    - "drop-net-raw-capability"
    - "env-var-secret"
    - "exposed-services"
    - "host-ipc"
    - "host-network"
    - "host-pid"
    - "mismatching-selector"
    - "no-anti-affinity"
    - "privilege-escalation-container"
    - "privileged-container"
    - "sensitive-host-mounts"
    - "ssh-port"
    - "unsafe-proc-mount"
    - "unsafe-sysctls"
    - "writable-host-mount"

customChecks:
  - name: "latest-tag"
    description: "Image uses 'latest' tag"
    template: "latest-tag"
    scope:
      objectKinds:
        - DeploymentLike
