apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
spec:
  chart:
    spec:
      chart: portainer
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: portainer
      version: 2.33.5
  interval: 10m0s
  values:
    trusted_origins:
      enabled: true
      domains: "port.heroaero.dev,port.heroaero.info"
    service:
      type: ClusterIP
      httpPort: 9000
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: port.heroaero.dev
          paths:
            - path: /
              port: 9000
      tls:
        - hosts:
            - port.heroaero.dev
          secretName: portainer-tls
    resources:
      requests:
        memory: "32Mi"
        cpu: "25m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    persistence:
      enabled: true
      size: 10Gi
      storageClass: nfs
      accessMode: ReadWriteOnce
