apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: vaultwarden
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: vaultwarden
