apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
  data:
    - secretKey: apiKey
      remoteRef:
        key: cloudflare-api-token
        property: CF_API_TOKEN
