apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-unifi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: homepage-secrets
    creationPolicy: Owner
  data:
    - secretKey: HOMEPAGE_VAR_UNIFI_USERNAME
      remoteRef:
        key: unifi
        property: username
    - secretKey: HOMEPAGE_VAR_UNIFI_PASSWORD
      remoteRef:
        key: unifi
        property: password
