apiVersion: external-secrets.io/v1
kind: ExternalSecret 
metadata:
  name: linkding-eso
  namespace: linkding25
spec:
  refreshInterval: 1m 
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore 
  target:
    name: linkding-secret 
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: linkding-secret 
