apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m
  path: ./platform/external-secrets/overlays/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube-homelab
  targetNamespace: external-secrets
