apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 30m0s
  # dependsOn:
  # - name: infra-configs
  retryInterval: 1m 
  timeout: 5m 
  sourceRef:
    kind: GitRepository
    name: flux-system 
  path: ./platform/external-secrets/overlays/staging
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 30m0s
  # dependsOn:
  # - name: infra-configs
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./platform/longhorn/overlays/staging
  prune: true
