apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "4.0.x"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: kube-system
  values:
    nfs:
      server: "10.6.6.117"
      path: "/mnt/storage/nfs/k8s"
    storageClass:
      name: nfs
      defaultClass: false
      reclaimPolicy: Retain
      archiveOnDelete: true
      accessModes: ReadWriteOnce
