apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store     
    kind: ClusterSecretStore
  target:
    name: postgresql
    creationPolicy: Owner
    template:
      data:
        POSTGRES_USER: "{{ .POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
        POSTGRES_DB: "{{ .POSTGRES_DB }}"
        DB_POSTGRESDB_USER: "{{ .POSTGRES_USER }}"
        DB_POSTGRESDB_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
        DB_POSTGRESDB_DATABASE: "{{ .POSTGRES_DB }}"
        DB_POSTGRESDB_HOST: "postgres.default.svc.cluster.local"
        DB_POSTGRESDB_PORT: "5432"

  dataFrom:
    - extract:
        key: postgresql 
