apiVersion: external-secrets.io/v1
kind: ExternalSecret 
metadata:
  name: postgresql
spec:
  refreshInterval: 1m 
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore 
  target:
    name: postgresql
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: postgresql
