apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-secret-store 
spec:
  interval: 1h
  path: ./platform/cluster-secret-store/overlays/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: aws
  wait: true
